title : SOSP22
name: 'Summer of Side Projects 2022'
description: '4 weeks of fun python workshops and guided side projects'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: Links
featured_posts:
  - url: '/ideas'
    title: 'Advice on Ideas'
  - url: '/workflow'
    title: 'Advice on Workflow'
  - url: /productive
    title: 'Advice on being Productive'
  - url: 'https://forum.sosp22.com/'
    title: 'Forum'
  # - url: 'https://forms.gle/UCkgCZvnzHjQwjQM8'
  #   title: Idea Form (by Wednesday Midnight)
  # - url: 'https://forms.gle/SdnQBowR7c8AuYeH8'
  #   title: Project Submission Form (by Monday Midnight)

collections:
  news:
    title: Info, Tutorials, and Advice
    default_open: false
    output: true
  posts:
    title: Workshops
    default_open: true
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Essays
      permalink: /:title
  - scope:
      type: news
    values:
      title: News
      permalink: /:title

plugins:
  - jekyll-sitemap
  - jekyll-toc
