title : SOSP22
name: 'Summer of Side Projects 2022'
description: '4 weeks of fun python workshops and guided side projects'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'
  - url: '#'
    title: 'Featured post #2'
  - url: '#'
    title: 'Featured post #3'

collections:
  news:
    title: Info, Tutorials, and Advice
    default_open: false
    output: true
  posts:
    title: Workshops
    default_open: true
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Essays
      permalink: /post/:title
  - scope:
      type: news
    values:
      title: News
      permalink: /news/:title

plugins:
  - jekyll-sitemap
  - jekyll-toc
